### PR TITLE
added sqlData and sqlAppendTable

### PR DESCRIPTION
**Pull request by r2evans**
(No issue fixes.)

Changes proposed:

- methodized `sqlData` and `sqlAppendTable`
- added tests (with "SQL_PROD" server available?)

@imanuelcostigan

### CODE REVIEW

**Comment by imanuelcostigan** [comment]
Thanks @r2evans. What's the motivation for this PR? NB: I have `sqlAppendTableTemplate()`

**Comment by r2evans** [comment]
I may be confused, but I've not been able to get it to work (well). The only way I see to use `sqlAppendTableTemplate` is row-by-row (as you do in `dbWriteTable`), but since (a) `dbWriteTable` does not provide the ability to return columns with default values (as in `uniqueidentifier`), and (b) write performance of row-by-row inserts is *horrible*, I need to find another way. (I'm working on another PR that will likely improve push performance by using `sqlAppendTable` instead of `sqlAppendTableTemplate`. I would REALLY prefer to use parameters, though, so please let me know if there's a way to use parameters with more than one row at a time.)

I'd like to be able to use `dbSendPreparedStatement`, but that isn't (yet) implemented for RSQLServer. Ultimately, I'd like to be able to send a subset of the columns of a table (not uploading an `id` field) and return the auto-`id` using something like "`insert into tablename (col1,col2) OUTPUT INSERTED.id values (...),(...)`". My big inserts are ~2M rows, so it really would benefit from being batched.

If you have alternatives, I'm certainly open to them; since I don't know enough to hack the jTDS side of things, I do what I can strictly in R.

If you're still open to the concept of this PR then **please wait**, there are two more changes that need to be made: (1) I realize I'm not properly quoting strings (need to use `dbQuoteString`), and (2) in working on RPostgres and RSQLite as well, I realize that `sqlData` is meant for a different transformation as `sqlAppendTable`.

BTW: an error in the build looks like the same error as fixed in your #100. Did I not update my fork correctly? I'll try to fetch and rebase in case that fixes the build.

**Comment by r2evans** [comment]
I've updated quoted strings. I know there are much better ways to deal with the prepared statements, but your code currently assumes `params` are of length one instead; I have seen examples in jTDS (such as [this one](https://www.mkyong.com/jdbc/jdbc-preparedstatement-example-batch-update/)) showing multi-row binding with a single execute), I just haven't sat down and played with the internals of rJava enough to know how to do it right.

If multi-row prepared statements are easily done, I agree that they would be better than this approach. In the meantime, I offer this as a slight improvement in performance at the expense of brute-forcing the db-quoting.

**Comment by imanuelcostigan** [comment]
I will close this PR given PR #114

**Pull request closed without merging**
