### PR TITLE
con_acquire and con_release methods for src_sqlserver

### PR DESCRIPTION
**Pull request by refik**
Fixes the error:
```
Error in UseMethod("con_acquire", src) :
  no applicable method for 'con_acquire' applied to an object of class "src_sqlserver"
```

when trying to use `copy_to.src_sqlserver`. I wanted to do a cross table join with two databases on the same server with the same `src_sqlserver`, but there was no way to specify the database name along with the table name while calling `dplyr::tbl(src, ...)`. The next best option was using `copy = TRUE` with seperate `tbl_sqlserver`, but it failed with the error above.

@imanuelcostigan

### CODE REVIEW

**Comment by imanuelcostigan** [comment]
I am not sure why this is required. Can you please provide a reproducible or even hypothetical R script example? Thanks

**Comment by refik** [comment]
Sure, this is the scenario where I had the error I mentioned:
```
conn_1 <- RSQLServer::src_sqlserver(server = "prod", database = "db1")
conn_2 <- RSQLServer::src_sqlserver(server = "prod", database = "db2")
tbl_1 <- dplyr::tbl(conn_1, "table_1")
tbl_2 <- dplyr::tbl(conn_2, "table_2")
dplyr::left_join(tbl_1, tbl_2, by = "column", copy = TRUE)
```
I can try to generate a reproducible example if necessary.

**Comment by imanuelcostigan** [comment]
What are your library calls?

**Comment by refik** [comment]
I think I was using an older version when I had that error. I'm not sure what happened. I wanted to show my session information so I tried to reproduce. I installed the latest development version and it worked without any problem. 

I want to ask though, is there a way to do that join I've shown in the example without needing `copy = TRUE`? @imanuelcostigan

**Pull request closed without merging**
